force-app/main/default/objects/Intervalle_de_temps__c/Intervalle_de_temps__c.object-meta.xml
<CustomObject>
    <label>Intervalle de temps</label>
    <nameField>
        <displayFormat>FDT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intervalle de temps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Intervalle_de_temps__c/fields/Date_de_debut__c.field-meta.xml
<CustomField>
    <fullName>Date_de_debut__c</fullName>
    <label>Date de debut</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Intervalle_de_temps__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <label>Date de fin</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Intervalle_de_temps__c/fields/Tache__c.field-meta.xml
<CustomField>
    <fullName>Tache__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tâche</label>
    <referenceTo>Tache__c</referenceTo>
    <relationshipName>Feuille_de_temps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Intervalle_de_temps__c/fields/Total_Heures__c.field-meta.xml
<CustomField>
    <fullName>Total_Heures__c</fullName>
    <label>Total Heures</label>
    <summarizedField>Saisie_de_temps__c.Heures__c</summarizedField>
    <summaryForeignKey>Saisie_de_temps__c.Feuille_de_temps__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Intervalle_de_temps__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Intervalle_de_temps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tache__c/Tache__c.object-meta.xml
<CustomObject>
    <description>Pour voir toutes les tâches des employés</description>
    <label>Tâche</label>
    <nameField>
        <label>📋 Nom de la tâche</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tâches</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Tache__c/fields/Date_de_fin__c.field-meta.xml
<CustomField>
    <fullName>Date_de_fin__c</fullName>
    <description>Date de fin de la tâche</description>
    <inlineHelpText>Date de fin de la tâche</inlineHelpText>
    <label>🏁 Date de fin</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tache__c/fields/Total_Heures__c.field-meta.xml
<CustomField>
    <fullName>Total_Heures__c</fullName>
    <label>⏰ Total Heures</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tache__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>👤 Affectée à</label>
    <referenceTo>User</referenceTo>
    <relationshipName>T_ches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IntervalleDeTempsController.cls
public with sharing class IntervalleDeTempsController {
    //false pour permettre le refresh après sauvegarde
    @AuraEnabled(cacheable=false)

    public static List<Intervalle_de_temps__c> getWeeklyIntervalleDeTempsController() {
        // Calcul des dates de début et de fin de la semaine en cours
        Date startOfWeek = Date.today().toStartOfWeek();
        Date endOfWeek = startOfWeek.addDays(6);
        
        // Requête sur "IntervalleDeTemps__c" pour récupérer les enregistrements de la semaine
        return [SELECT Id, User__c, Name, Date_de_debut__c, Date_de_fin__c,  Tache__r.Name, Total_Heures__c
                FROM Intervalle_de_temps__c WHERE Date_de_debut__c >= :startOfWeek AND Date_de_fin__c <= :endOfWeek
                ];
    }
}